### ISSUE TITLE
Could you help me how to run test this source please?

### ISSUE THREAD

**Issue by bboynam99** [nionis/dubiex#3]
I see truffle command but don't know how to run it

**Comment by nionis** [comment]
1. clone it
2. create [keys.js](https://github.com/nionis/dubiex/blob/master/truffle-config.js)
this is a function that takes in the network you work on, and returns useful secrets / keys
3. npm install
4. npx truffle develop
5. here u can either migrate or run tests (look into truffle documentation)

**Comment by bboynam99** [comment]
Thank you for your replying
I got stuck at keys.js, is it emty or input anything else please?

**Comment by bboynam99** [comment]
is it correct if i input in keys.js:

```
rinkeby= 'my rinkeby project infura id'
mainnet='my mainnet project infura id'
```

**Comment by nionis** [comment]
it should look more or less something like this

```javascript
module.exports = (network) => {
  if (network === "mainnet") {
    return {
      mnemonic: "xx",
      infuraKey: "xx",
    }
  } else {
    return {
      mnemonic: "xx",
      infuraKey: "xx",
    }
  }
}
```

**Comment by bboynam99** [comment]
thank you,
I fail ai truffle compile, it says errorpaser....somthing...
maybe i will try later
